import { Volunteer, Slot } from './api';

export const mockVolunteers: Volunteer[] = [
  {
    id: 1,
    name: 'Sarah Johnson',
    phone: '+1 (555) 123-4567',
    email: 'sarah.johnson@email.com',
    address: '123 Oak Street, Springfield, IL 62701',
    group: 1,
    points: 245,
    booked_slots: 12,
    status: 'active',
  },
  {
    id: 2,
    name: 'Michael Chen',
    phone: '+1 (555) 234-5678',
    email: 'michael.chen@email.com',
    address: '456 Maple Avenue, Chicago, IL 60601',
    group: 2,
    points: 189,
    booked_slots: 8,
    status: 'active',
  },
  {
    id: 3,
    name: 'Emily Rodriguez',
    phone: '+1 (555) 345-6789',
    email: 'emily.rodriguez@email.com',
    address: '789 Pine Road, Austin, TX 78701',
    group: 1,
    points: 312,
    booked_slots: 15,
    status: 'active',
  },
  {
    id: 4,
    name: 'David Thompson',
    phone: '+1 (555) 456-7890',
    email: 'david.thompson@email.com',
    address: '321 Elm Street, Boston, MA 02101',
    group: 3,
    points: 156,
    booked_slots: 6,
    status: 'inactive',
  },
  {
    id: 5,
    name: 'Lisa Anderson',
    phone: '+1 (555) 567-8901',
    email: 'lisa.anderson@email.com',
    address: '654 Birch Lane, Seattle, WA 98101',
    group: 2,
    points: 278,
    booked_slots: 11,
    status: 'active',
  },
  {
    id: 6,
    name: 'James Wilson',
    phone: '+1 (555) 678-9012',
    email: 'james.wilson@email.com',
    address: '987 Cedar Court, Denver, CO 80201',
    group: 1,
    points: 423,
    booked_slots: 18,
    status: 'active',
  },
  {
    id: 7,
    name: 'Maria Garcia',
    phone: '+1 (555) 789-0123',
    email: 'maria.garcia@email.com',
    address: '147 Spruce Drive, Miami, FL 33101',
    group: 3,
    points: 201,
    booked_slots: 9,
    status: 'active',
  },
  {
    id: 8,
    name: 'Robert Lee',
    phone: '+1 (555) 890-1234',
    email: 'robert.lee@email.com',
    address: '258 Willow Way, Portland, OR 97201',
    group: 2,
    points: 134,
    booked_slots: 5,
    status: 'inactive',
  },
];

export const mockSlots: Record<number, Slot[]> = {
  1: [
    {
      id: 101,
      volunteer_id: 1,
      date: '2025-12-01',
      time: '09:00',
      description: 'Community food drive at Central Park',
      status: 'confirmed',
    },
    {
      id: 102,
      volunteer_id: 1,
      date: '2025-12-05',
      time: '14:00',
      description: 'Senior home visit and activities',
      status: 'confirmed',
    },
    {
      id: 103,
      volunteer_id: 1,
      date: '2025-12-10',
      time: '10:30',
      description: 'Beach cleanup initiative',
      status: 'pending',
    },
    {
      id: 104,
      volunteer_id: 1,
      date: '2025-12-26', // Matching the "Vr 26 Dec" in screenshot roughly
      time: '19:30 - 22:00',
      description: 'Bar service Thursday 7:30 PM - 10:00 PM',
      status: 'confirmed',
    },
    {
      id: 104,
      volunteer_id: 1,
      date: '2025-11-15',
      time: '15:00',
      description: 'Library book sorting',
      status: 'confirmed',
    },
  ],
  2: [
    {
      id: 201,
      volunteer_id: 2,
      date: '2025-12-02',
      time: '11:00',
      description: 'Youth mentorship program',
      status: 'confirmed',
    },
    {
      id: 202,
      volunteer_id: 2,
      date: '2025-12-08',
      time: '16:00',
      description: 'Animal shelter assistance',
      status: 'pending',
    },
    {
      id: 203,
      volunteer_id: 2,
      date: '2025-11-20',
      time: '13:00',
      description: 'Community garden maintenance',
      status: 'confirmed',
    },
  ],
  3: [
    {
      id: 301,
      volunteer_id: 3,
      date: '2025-12-03',
      time: '08:00',
      description: 'Hospital volunteer shift',
      status: 'confirmed',
    },
    {
      id: 302,
      volunteer_id: 3,
      date: '2025-12-07',
      time: '12:00',
      description: 'Homeless shelter meal service',
      status: 'confirmed',
    },
    {
      id: 303,
      volunteer_id: 3,
      date: '2025-12-12',
      time: '14:30',
      description: 'School tutoring session',
      status: 'pending',
    },
    {
      id: 304,
      volunteer_id: 3,
      date: '2025-12-15',
      time: '10:00',
      description: 'Park trail maintenance',
      status: 'confirmed',
    },
    {
      id: 305,
      volunteer_id: 3,
      date: '2025-11-10',
      time: '09:00',
      description: 'Charity run event support',
      status: 'cancelled',
    },
  ],
  4: [
    {
      id: 401,
      volunteer_id: 4,
      date: '2025-12-04',
      time: '15:00',
      description: 'Food bank sorting',
      status: 'pending',
    },
    {
      id: 402,
      volunteer_id: 4,
      date: '2025-11-18',
      time: '11:00',
      description: 'Community cleanup',
      status: 'confirmed',
    },
  ],
  5: [
    {
      id: 501,
      volunteer_id: 5,
      date: '2025-12-06',
      time: '13:00',
      description: 'Environmental awareness workshop',
      status: 'confirmed',
    },
    {
      id: 502,
      volunteer_id: 5,
      date: '2025-12-09',
      time: '10:00',
      description: 'Tree planting initiative',
      status: 'confirmed',
    },
    {
      id: 503,
      volunteer_id: 5,
      date: '2025-12-14',
      time: '16:00',
      description: 'Community center event setup',
      status: 'pending',
    },
  ],
  6: [
    {
      id: 601,
      volunteer_id: 6,
      date: '2025-12-01',
      time: '14:00',
      description: 'Disaster relief supply sorting',
      status: 'confirmed',
    },
    {
      id: 602,
      volunteer_id: 6,
      date: '2025-12-05',
      time: '09:00',
      description: 'Blood drive coordination',
      status: 'confirmed',
    },
    {
      id: 603,
      volunteer_id: 6,
      date: '2025-12-11',
      time: '11:30',
      description: 'Clothing donation center',
      status: 'confirmed',
    },
    {
      id: 604,
      volunteer_id: 6,
      date: '2025-11-22',
      time: '15:00',
      description: 'Thanksgiving meal prep',
      status: 'confirmed',
    },
  ],
  7: [
    {
      id: 701,
      volunteer_id: 7,
      date: '2025-12-03',
      time: '10:00',
      description: 'Senior tech help sessions',
      status: 'confirmed',
    },
    {
      id: 702,
      volunteer_id: 7,
      date: '2025-12-13',
      time: '14:00',
      description: 'Art therapy for kids',
      status: 'pending',
    },
  ],
  8: [
    {
      id: 801,
      volunteer_id: 8,
      date: '2025-12-08',
      time: '12:00',
      description: 'Community sports coaching',
      status: 'pending',
    },
  ],
};

let nextSlotId = 1000;

export const getNextSlotId = () => {
  nextSlotId += 1;
  return nextSlotId;
};
